apiVersion: v1
kind: Service
metadata:
  name: console
spec:
  selector:
    app: console
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: basecamp/console
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: mysql-secret
              prefix: MYSQL_
          ports:
            - containerPort: 3000