apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: nextjs
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: storybook
    protocol: TCP
    port: 6006
    targetPort: 6006

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frnotend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: basecamp/frontend
        ports:
        - containerPort: 3000
        - containerPort: 6006
        envFrom:
        - configMapRef:
            name: frontend-config