apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
spec:
  storageClassName: manual
  volumeName: mysql-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/Shared/k8s/backend/mysql