apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-env
data:
  DATABASE: database_development
  DATABASE_TEST: database_test
  USER: mysql_user
  PASSWORD: development_pass
  ROOT_PASSWORD: password

