apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: basecamp/mysql
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-volume
      mountPath: /var/lib/mysql
    envFrom:
      - configMapRef:
          name: mysql-env
  volumes:
  - name: mysql-volume
    persistentVolumeClaim:
      claimName: mysql-volume