version: '3.7'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./services/frontend
      target: dev
    volumes:
      - ./services/frontend/src:/app/src:delegated
      - ./services/frontend/package.json:/app/package.json:delegated
      - ./services/frontend/package-lock.json:/app/package-lock.json:delegated
      - ./services/frontend/tsconfig.json:/app/tsconfig.json:delegated
      - ./services/frontend/config:/app/config:delegated
    ports:
      - "3001:3000"
    environment:
      TZ: Asia/Tokyo
  console:
    build:
      dockerfile: Dockerfile
      context: services/console
      target: dev
    volumes:
      - ./services/console:/app:delegated
      - ./services/proto:/proto:delegated
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DATABASE_DEVELOPMENT: database_development
      DATABASE_TEST: database_test
      RAILS_MAX_THREADS: 5
      DATABASE_USER: mysql_user
      DATABASE_PASSWORD: development_pass
      DATABASE_HOST: mysql
      TZ: Asia/Tokyo
  mysql:
    image: mysql:8.0.16
    environment:
      MYSQL_DATABASE: database_development
      MYSQL_DATABASE_TEST: database_test
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: development_pass
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./services/mysql/initdb.d:/docker-entrypoint-initdb.d:delegated
      - ./services/mysql/data:/var/lib/mysql:delegated
      - ./services/mysql/conf.d:/etc/mysql/conf.d:delegated
    ports:
      - "3306:3306"
