apiVersion: skaffold/v1
kind: Config
metadata:
  name: basecamp
build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
profiles:
  - name: development
    build:
      local:
        push: false
      artifacts:
        - image: basecamp/frontend
          context: services/frontend
          sync:
            manual:
              - src: "**/*"
                dest: "/app"
          docker:
            dockerfile: ./Dockerfile
            target: dev
#        - image: basecamp/backend
#          context: services/backend
#          sync:
#            manual:
#              - src: "src/**/*"
#                dest: "/go/src/backend"
#                strip: "src"
#          docker:
#            dockerfile: ./Dockerfile
#            target: dev
        - image: basecamp/mysql
          context: services/mysql
          docker:
            dockerfile: ./Dockerfile
            target: dev
        - image: basecamp/console
          context: services/console
          sync:
            manual:
              - src: "**/*"
                dest: "/app"
          docker:
            dockerfile: ./Dockerfile
            target: dev
    deploy:
      kustomize:
        path: infrastructure/k8s/overlays/development
      helm:
        releases:
          - name: argo-minio
            chartPath: charts/argo-minio
            skipBuildDependencies: true
            valuesFiles:
              - charts/values/argo-minio.yaml
          - name: argo
            chartPath: charts/argo
            skipBuildDependencies: true
            valuesFiles:
              - charts/values/argo.yaml
