openapi: 3.0.3
info:
  # 必須パラメーター。アプリケーションのバージョン
  version: 0.0.1
  # 必須パラメーター。このAPI仕様書を用いて作成するアプリケーションのタイトル。
  title: Training Menu API
  # 任意パラメーター。アプリケーションについての説明
  descriptsion: A simple menu for exercise
  basePath: /training/v1
servers:
# 必須パラメーター。APIターゲットホストのURL。
- url: http://localhost/training/v1

# エンドポイントを記載するオブジェクト
paths:
  # パスとして/plansを定義している。
  /plans:
    # REST APIのメソッド。ここではパス/plansに対し、GETメソッドを定義している。
    get:
      # 任意パラメーター。パス/plansに対し定義したGETメソッドについての説明。
      description: Return a list of training plans
      parameters:
        - $ref: '#/components/parameters/pageLimit'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: Successfully returned a list of training plans
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plan'
        '400':
          $ref: '#/components/responses/400Error'
    post:
      description: Registar a new plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plan'
      responses:
        '200':
          description: Successfully returned a list of training plans
        '400':
          $ref: '#/components/responses/400Error'

  /plans/{planner_name}:
    get:
      description: Get information about the plan registered by the described planner
      parameters:
      - name: planner_name
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully returned a list of training plans
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plan'
        '400':
          $ref: '#/components/responses/400Error'

components:
  schemas:
    plan:
      type: object
      required:
      - plan_id
      properties:
        plan_id:
          type: integer
        plan_name:
          type: string
        planner_name:
          type: string
        duration:
          type: integer
        difficulty:
          type: integer
  parameters:
    pageLimit:
      name: limit
      in: query
      description: Limit the number of plans on a page
      schema:
        type: integer
    pageOffset:
      name: offset
      in: query
      description: Specifies the page number of the plans to be displayed
      schema:
        type: integer
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string