enum Env {
  BFF_ENV = "BFF_ENV",
  BFF_HOST = "BFF_HOST",
  BFF_PORT = "BFF_PORT",
  BFF_ALLOW_ORIGIN_HOSTS = "BFF_ALLOW_ORIGIN_HOSTS",
  BFF_ADMIN_CREDENTIAL = "BFF_ADMIN_CREDENTIAL",
  BFF_SECURE_COOKIE = "BFF_SECURE_COOKIE",
  BACKEND_ENDPOINT = "BACKEND_ENDPOINT",
}

export default Env;
