openapi: 3.0.3
info:
  # 必須パラメーター。アプリケーションのバージョン
  version: 0.0.1
  # 必須パラメーター。このAPI仕様書を用いて作成するアプリケーションのタイトル。
  title: basecamp backend
servers:
  # 必須パラメーター。APIターゲットホストのURL。
  - url: http://console/
# エンドポイントを記載するオブジェクト
paths:
  /api/v1/users:
    post:
      description: "ユーザーの初期データを構築するためのAPI"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - uid
              properties:
                email:
                  type: string
                uid:
                  description: "Firebase Authentication ユーザーのID"
                  type: string
      responses:
        '201':
          description: Successfully returned a list of training plans
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Create Initial Data Failed Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

